spring:
  application:
    name: anycomp-marketplace
  datasource:
    url: jdbc:postgresql://localhost:5432/anycomp_db
    username: postgres
    password: Postgres1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect